# Basic config file for downstream classification task.

path_to_data_split:
  desc: Path to Pickle file containing train and validation paths for images that should be trained on.
  value: "/sc-scratch/sc-scratch-gbm-radiomics/tcia/manifest-1654187277763/nifti/FDG-PET-CT-Lesions-trans/split.pkl"

path_to_model:
  desc: Path to saved model state dict.
  value: "/sc-scratch/sc-scratch-gbm-radiomics/meddist_models/simple/vermilion-dragon-60_2gh75m4i/DenseNet_epoch043.pt"

retrain_backbone:
  desc: If true, the backbone will be retrain.
  value: false

output_path:
  desc: Path to save all checkpoints.
  value: "/sc-scratch/sc-scratch-gbm-radiomics/meddist_models/simple/vermilion-dragon-60_2gh75m4i/"

epochs:
  desc: Number of epochs to train over
  value: 50

pos_weight:
  desc: A weight of positive examples for the pytorch BCEWithLogitsLoss.
  value: 3.0

number_of_crops:
  desc: Crops sampled per patient. This is the same as batch size in this training logic.
  value: 32

crop_size:
  desc: Spatial size of crops.
  value: 64

lr:
  desc: Learning rate
  value: 0.001

embedding_size:
  desc: Size of the feature vector of the trained model.
  value: 1024

augment:
  desc: Whether to add simple intensity augmentation. They are applied on the full image.
  value: False
