# Basic config file to train SimCLR model.

model:
  desc: Model type to be trained. Choose between simclr, meddist, ...
  value: simclr

path_to_data_split:
  desc: Path to Pickle file containing train and validation paths for images that should be trained on.
  value: "/sc-scratch/sc-scratch-gbm-radiomics/tcia/manifest-1654187277763/nifti/FDG-PET-CT-Lesions-trans/split.pkl"

output_path:
  desc: Path to save all checkpoints.
  value: "/sc-scratch/sc-scratch-gbm-radiomics/meddist_models/simclr"

epochs:
  desc: Number of epochs to train over
  value: 50

number_of_crops:
  desc: Crops sampled per patient. This is the same as batch size in this training logic.
  value: 256

crop_size:
  desc: Size of the crop.
  value: 32

batch_size:
  desc: From how many patients we will take the crops. ATTENTION The total batch size is batch_size * number_of_crops
  value: 1

lr:
  desc: Learning rate
  value: 0.001

embedding_size:
  desc: Size of the feature vector of the trained model.
  value: 1024

temperature:
  desc: TODO
  value: 0.05